version: "1"
rules:                      
  - base: master           
    upstream: nginx-proxy:master 
    mergeMethod: merge  	
    assignees:              
      - freekers
    reviewers:       
      - freekers
